# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=150)),
                ('sp', models.CharField(max_length=150)),
                ('key', models.BigIntegerField()),
                ('beginCall', models.DateTimeField()),
                ('origin', models.BigIntegerField()),
                ('callAnswered', models.BooleanField(default=False)),
                ('lastState', models.CharField(max_length=150)),
                ('IVRSel', models.BigIntegerField()),
                ('dialIntentBegin1', models.DateTimeField()),
                ('dialIntentCaller1', models.BigIntegerField()),
                ('dialIntentCalled1', models.BigIntegerField()),
                ('dialIntentEnd1', models.DateTimeField()),
                ('dialIntentAnswered1', models.BooleanField()),
                ('sessionFile', models.CharField(blank=True, max_length=255, null=True)),
                ('hc', models.CharField(max_length=150)),
                ('routing', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('endDial', models.DateTimeField()),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
    ]
