# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_call', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de llamada')),
                ('origin', models.BigIntegerField(blank=True, null=True, verbose_name='N\xfamero que llama')),
                ('call_answered', models.BooleanField(default=False, verbose_name='Contest\xf3 el IVR')),
                ('last_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Opci\xf3n seleccioanda del IVR')),
                ('ivr_sel', models.BigIntegerField(blank=True, null=True, verbose_name='Tecla que presion\xf3')),
                ('dial_intent_begin', models.DateTimeField(blank=True, null=True, verbose_name='Hora de inicio de llamado de tranferencia')),
                ('dial_intent_caller', models.BigIntegerField(blank=True, null=True, verbose_name='N\xfamero que llama')),
                ('dial_intent_called', models.BigIntegerField(blank=True, null=True, verbose_name='N\xfamero a donde se transfiere la llamada')),
                ('dial_intent_end', models.DateTimeField(blank=True, null=True, verbose_name='T\xe9rmino de la llamada de transferencia')),
                ('dial_intent_answered', models.BooleanField(default=False, verbose_name='La transferencia fue contestada')),
                ('session_file', models.FileField(null=True, upload_to='audio/%Y/%m/%d1460734146', verbose_name='Archivo de audio')),
                ('hc', models.CharField(blank=True, max_length=150, null=True, verbose_name='C\xf3digo de t\xe9rmino de la llamada')),
                ('end_dial', models.DateTimeField(blank=True, null=True, verbose_name='T\xe9rmino de la llamada')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del registro')),
            ],
        ),
    ]
