# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='session_file',
            field=models.FileField(null=True, upload_to='media/%Y/%m/%d1461246145', verbose_name='Archivo de audio'),
        ),
    ]
