# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_auto_20160519_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='dialIntentEnd1',
            field=models.DateTimeField(null=True),
        ),
    ]
