# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_auto_20160520_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='hc',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='sp',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
