# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendGridConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(db_index=True, max_length=255)),
                ('api_user', models.CharField(db_index=True, max_length=200)),
                ('api_pass', models.CharField(db_index=True, max_length=200)),
                ('email_from', models.EmailField(db_index=True, max_length=255)),
                ('email_from_name', models.CharField(db_index=True, max_length=255)),
                ('email_subject', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(db_index=True, max_length=200)),
                ('html_template', models.TextField()),
            ],
        ),
    ]
